// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHMYzzkZVQ3b5bot_9XYQpLd41yrGfCRQ',
    appId: '1:1016311301761:web:ee06088bf54b4428976f80',
    messagingSenderId: '1016311301761',
    projectId: 'kisan-desk',
    authDomain: 'kisan-desk.firebaseapp.com',
    databaseURL: 'https://kisan-desk-default-rtdb.firebaseio.com',
    storageBucket: 'kisan-desk.firebasestorage.app',
    measurementId: 'G-NLBVM6E2P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xv9MQcNcKFwwZNZvFh02b0PZYbqPO1o',
    appId: '1:1016311301761:android:40e9f5043edb8c9c976f80',
    messagingSenderId: '1016311301761',
    projectId: 'kisan-desk',
    databaseURL: 'https://kisan-desk-default-rtdb.firebaseio.com',
    storageBucket: 'kisan-desk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBIwAnZ_MgaiO2wyNcXv8imPOsBd_oeQ',
    appId: '1:1016311301761:ios:9964155cd9998327976f80',
    messagingSenderId: '1016311301761',
    projectId: 'kisan-desk',
    databaseURL: 'https://kisan-desk-default-rtdb.firebaseio.com',
    storageBucket: 'kisan-desk.firebasestorage.app',
    androidClientId: '1016311301761-rg7bl7gp58j3gklqe37aff8mkcs1keqo.apps.googleusercontent.com',
    iosClientId: '1016311301761-jahbujv72v87b8s6bsjb2qasofe99peu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBIwAnZ_MgaiO2wyNcXv8imPOsBd_oeQ',
    appId: '1:1016311301761:ios:9964155cd9998327976f80',
    messagingSenderId: '1016311301761',
    projectId: 'kisan-desk',
    databaseURL: 'https://kisan-desk-default-rtdb.firebaseio.com',
    storageBucket: 'kisan-desk.firebasestorage.app',
    androidClientId: '1016311301761-rg7bl7gp58j3gklqe37aff8mkcs1keqo.apps.googleusercontent.com',
    iosClientId: '1016311301761-jahbujv72v87b8s6bsjb2qasofe99peu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainproject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHMYzzkZVQ3b5bot_9XYQpLd41yrGfCRQ',
    appId: '1:1016311301761:web:b36e72ef7af4c4b5976f80',
    messagingSenderId: '1016311301761',
    projectId: 'kisan-desk',
    authDomain: 'kisan-desk.firebaseapp.com',
    databaseURL: 'https://kisan-desk-default-rtdb.firebaseio.com',
    storageBucket: 'kisan-desk.firebasestorage.app',
    measurementId: 'G-EWRNWQ4PW0',
  );
}
